### ISSUE TITLE
Blank page on react-photonkit.github.io

### ISSUE THREAD

**Issue by HaNdTriX** [react-photonkit/react-photonkit.github.io#2]
When I visit http://react-photonkit.github.io/ I am getting a blank page.

<img width="639" alt="screen shot 2016-08-20 at 07 14 54" src="https://cloud.githubusercontent.com/assets/1265681/17831109/de18d08a-66a5-11e6-8886-7da8f5303279.png">

**Comment by ragingwind** [comment]
Thanks for sharing. I will check it

**Comment by ragingwind** [comment]
Closed by https://github.com/react-photonkit/react-photonkit.github.io/commit/0c25149d3a3d9d556f8511c370d8088f9997e9f7
